const skillList = [
  { id: "python", name: "[Python]" },
  { id: "javascript", name: "[JavaScript]" },
  { id: "typescript", name: "[TypeScript]" },
  { id: "java", name: "[Java]" },
  { id: "c", name: "[C]" },
  { id: "cpp", name: "[C++]" },
  { id: "go", name: "[Go]" },
  { id: "dart", name: "[Dart]" },
  { id: "bash", name: "[Bash]" },
  { id: "react", name: "[React]" },
  { id: "nextjs", name: "[Next.js]" },
  { id: "html", name: "[HTML]" },
  { id: "css", name: "[CSS]" },
  { id: "tailwind", name: "[Tailwind CSS]" },
  { id: "flutter", name: "[Flutter]" },
  { id: "redux", name: "[Redux]" },
  { id: "nodejs", name: "[Node.js]" },
  { id: "express", name: "[Express]" },
  { id: "fastapi", name: "[FastAPI]" },
  { id: "postgresql", name: "[PostgreSQL]" },
  { id: "mysql", name: "[MySQL]" },
  { id: "mongodb", name: "[MongoDB]" },
  { id: "prisma", name: "[Prisma]" },
  { id: "redis", name: "[Redis]" },
  { id: "firebase", name: "[Firebase]" },
  { id: "supabase", name: "[Supabase]" },
  { id: "appwrite", name: "[Appwrite]" },
  { id: "azure", name: "[Azure]" },
  { id: "arduino", name: "[Arduino]" },
  { id: "raspberrypi", name: "[Raspberry Pi]" },
  { id: "git", name: "[Git]" },
  { id: "github", name: "[GitHub]" },
  { id: "gitlab", name: "[GitLab]" },
  { id: "vscode", name: "[VS Code]" },
  { id: "linux", name: "[Linux]" },
  { id: "docker", name: "[Docker]" },
  { id: "postman", name: "[Postman]" },
  { id: "figma", name: "[Figma]" },
];

export const skills = skillList.map((skill) => ({
  name: skill.name,
  icon: `https://skillicons.dev/icons?i=${skill.id}&theme=dark`,
}));
